In [1]:
import tensorflow as tf
import numpy as np

2024-07-28 13:47:25.174969: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-28 13:47:25.215944: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


VOC-NOTICE: GPU memory for this assignment is capped at 1024MiB


2024-07-28 13:47:27.390747: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [6]:
## create a tensorflow variable 
#scalar
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
rank_0_tensor.shape

tf.Tensor(4, shape=(), dtype=int32)


TensorShape([])

In [4]:
a = 4 #python 
a = np.array([4]) #numpy

In [7]:
#vector
rank_1_tensor = tf.constant([2.0, 4.0,5.0])
print(rank_1_tensor)
rank_1_tensor.shape

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


TensorShape([3])

In [9]:
#matrix 
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print(rank_2_tensor.shape)
print(rank_2_tensor.dtype)

(3, 2)
<dtype: 'float16'>


In [10]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]])
print(rank_2_tensor.dtype)

<dtype: 'int32'>


In [11]:
rank_2_tensor = tf.constant([[1.0, 2.0],
                             [3.0, 4.0],
                             [5.0, 6.0]])
print(rank_2_tensor.dtype)

<dtype: 'float32'>


In [12]:
rank_2_tensor = tf.constant([[1.0, 2.0],
                             [3.0, 4.0],
                             [5.0, 6.0]], dtype=tf.float64)
print(rank_2_tensor.dtype)

<dtype: 'float64'>


In [15]:
#tensor
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [16]:
#convert tensorflow into numpy
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [17]:
## create  two tensor object
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

In [18]:
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [19]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [20]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [22]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [23]:
print(tf.math.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [24]:
print(tf.nn.softmax(c))

tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [25]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])


In [26]:
print(tf.multiply(x, 2))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [27]:
print(x * y)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [28]:
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [29]:
#reshaping
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [30]:
reshaped = tf.reshape(x , [1,3])
reshaped.shape

TensorShape([1, 3])

In [31]:
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [32]:
reshaped

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [33]:
#ragged tensor 
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]

In [34]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [36]:
ragged_tensor.shape

TensorShape([4, None])

In [37]:
#creating a string 
scalar_string_tensor = tf.constant("gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)
